### ISSUE TITLE
Setup Failed - The system cannot find the file specified

### ISSUE THREAD

**Issue by MJongbloed** [patrickmoore/Mu#2]
Hi Patrick,

It seems as if the link to the Microsoft VC_redist.x64.exe in the installer is broken. During installation I get this error message:

Setup Failed
One or more issues caused the setup to fail. Please fix the issues and then retry setup. For more information see the log file.
0x80070002 - The system cannot find the file specified.

Any way I can get around this error?

Best Whishes Michel
[Mu_-_Telemetry_Exporter_for_iRacing_20160715200311.txt](https://github.com/patrickmoore/Mu/files/366599/Mu_-_Telemetry_Exporter_for_iRacing_20160715200311.txt)

**Comment by patrickmoore** [comment]
Microsoft changed the location of the redistributable.  I'll have to update the installer with the new link.  I'm also going to change the install of the redistributable to not be required for a successful installation.

**Comment by patrickmoore** [comment]
Should be fixed with v1.7.3.0
