### ISSUE TITLE
Lap Triggers and Track Maps\Layouts

### ISSUE THREAD

**Issue by Hazeltine29** [patrickmoore/Mu#27]
Since the 2022 S3 update I have had issues with Mu converting lap triggers and\or creating track maps\layouts correctly. I do not know if it is a lap trigger issue or if they changed how they are doing the GPS in the files but something is not correct. It has happen in the Global MX-5 car as well as the Aston and Mercedes GT4. The tracks I have run since the update that have had issues are Watkins Glen, Road Atlanta, and Phillip Island. I have included a link to my last race in the Aston GT4 at Watkins that displays the issue the best\worst. I also have a file that insists on the start\finish line being placed after turn 7 at Road Atlanta if your investigation needs additional data.

[Link](https://drive.google.com/file/d/1CbmkoF0cWdHca9lkv8HJ_zduvGThyuEj/view?usp=sharing)

Thanks in advance.

**Comment by Hazeltine29** [comment]
I am using Lat and Lon provided in the converted file.

**Comment by Hazeltine29** [comment]
Did that too. It is not significantly different from the provided Lat\Lon channels. Lap 11 still triggers about 80m too late which leaves lap 12 80m too short. Lap 27 is like a 1 2\3 of a lap and then teleports back to the S\F line for the start of Lap 28 even though that's not where I was. There were no spins or off tracks in any of laps 4-28. 

The data lines up to the time and distance traveled from the beginning. It is just really hard to tell what everything is because the sectors and lap numbers do not line up.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/66399916/176328339-4496604e-ff31-4b54-ae3f-ad9de18821a8.png">

**Comment by patrickmoore** [comment]
Thanks for the extra info, it was enough for me to isolate the problem. iRacing has updated how some of the channels work and some data that was not being expected was being processed incorrectly causing the Motec Beacons to go out of sync with the lap.  I'll get a new update out with the fix.
