### ISSUE TITLE
Yaml-cpp: error at line 0, column 0: bad conversion

### ISSUE THREAD

**Issue by GianlucaBelardinelli** [patrickmoore/Mu#3]
Hi,

I just recorded now a stint and while converting the file using your tool I get the following error:
`[Error] yaml-cpp: error at line 0, column 0: bad conversion`
Mu version: 1.7.3.2

**Comment by patrickmoore** [comment]
Hi Gianluca.  Are you able to send me offending .ibt file?

**Comment by GianlucaBelardinelli** [comment]
You have a dropbox file shared. Check your Gmail. I've used the one on the Mu readme description.

Thanks

**Comment by patrickmoore** [comment]
The problem is due to malformed YAML coming from iRacing.  Specifically, the DriverSetupName node is not quoted.  I've sent a message to David Tucker about the issue but I'll also add in this sanitizing case to Mu.

**Comment by patrickmoore** [comment]
Fixed with 1.7.3.3
