### ISSUE TITLE
Mu fails to exit when closed

### ISSUE THREAD

**Issue by thoraxe** [patrickmoore/Mu#4]
After hitting the "close"/x button, Mu continues to run in the background. It never terminates/exits. The process is still there in process viewer, and trying to restart it results in "Mu is already running".

* Win7 Ultimate, x64
* Mu 1.8.2.0

If it does exit, it takes longer than I waited (60+ seconds).

Mu is being run without iRacing running at all.

**Comment by patrickmoore** [comment]
Hitting the 'X' button only closes the UI for Mu. It will by design continue to run in the background.  To exit the process, right click on the icon in the system tray (lower right corner by the clock) and select Exit.

**Comment by thoraxe** [comment]
OH! 

Would you mind if I added that to the README as a PR?

**Comment by patrickmoore** [comment]
Yeah, that would be great!
