### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Viscaal** [patrickmoore/Mu#8]
Dear patrickmoore, 
I am trying to download mu conferter, but the same error is shown every time. 
error code: 0x80070666
could you have a look at this problem?

Looking forward to hearing from you, 

kind regards 
Bent Viscaal

**Comment by patrickmoore** [comment]
What version of Mu are you trying to install?  The latest versions do not install the vc++ redistributable, which would generate that error.

**Comment by Viscaal** [comment]
Thank you very much Patrick, you were right. I was trying to download the old version. Thanks again
